
/****************************************************************************

    config.c

 ***************************************************************************/

extern int  FAR PASCAL Config(HWND hWnd, HANDLE hInstance);
extern void FAR PASCAL ConfigRemove(void);
extern int  FAR PASCAL _loadds ConfigDlgProc(HWND hDlg, WORD msg, WORD wParam, LONG lParam);

extern BOOL fConfig;

