/* FMCFG.H - Jamie O'Connell */

#define DLG_FMCTL       43   

#define IDC_VERSTR      101
#define IDC_STEREO      102
#define IDC_PERCUSSION  103
#define IDC_PERCHAN     104
#define IDC_NVOC        105
#define IDC_VIB         106
#define IDC_TREM        107
#define IDC_BEND        108
#define IDC_BNKLBOX     109
#define IDC_BROWSE      110
#define IDC_BNKPATH     111
#define IDC_REMOVE      112 
#define IDC_HELP        113
#define IDC_RESET       114

#define IDC_CHAN1       115
#define IDC_CHAN2       116
#define IDC_CHAN3       117
#define IDC_CHAN4       118
#define IDC_CHAN5       119
#define IDC_CHAN6       120
#define IDC_CHAN7       121
#define IDC_CHAN8       122
#define IDC_CHAN9       123
#define IDC_CHAN10      124
#define IDC_CHAN11      125
#define IDC_CHAN12      126
#define IDC_CHAN13      127
#define IDC_CHAN14      128
#define IDC_CHAN15      129
#define IDC_CHAN16      130
#define IDC_DFTBANK     131
#define IDC_SAVESET     132
#define IDC_PERCBOOST   133
#define IDC_SET         134
#define IDC_TIMBRESET   135
#define IDC_REGSHADOW   136
#define IDC_FIXEDPITCH  137
#define IDC_TEST        138
#define IDC_WRITEPARMS  139

#define ID_PBST_SPIN                    160
#define ID_PCHN_SPIN                    161
#define ID_BND_SPIN                     162

int FAR PASCAL DoFMCtlDlg(HWND hParent);

